* Setting up boat

  In order to get the boat set up as efficiently as possible follow these guidelines. It is important to get the boat set up efficiently so that we can get out and hoist the sails to make sure the rigging is correct before starting the race.

   - Leave your bags on the dock when you arrive. We will load them as a team.
   - Get your crew assignment and make sure your area is set up. If your area overlaps with another crew make sure to coordinate with them
   - If your area is set up be available to help other people or work on tasks relating to disembarking, but do not take over another area or disrupt another area. Asking questions or getting in the way are some common ways to disrupt folks. If you are finished with your area and have questions, ask Mark or myself if one of us is not busy.

** General order for setting up boat

   1. General setup. This can be done by one or two people before the majority of the crew shows up and can be done even if you do not have your crew assignment.
      - Remove power cable. Leave on dock behind dock box. Make sure to close door on outlet
      - Remove canvas from binnacle and main.
      - Check the engine oil and coolant. Do this before throwing lines down the companionway

   2. Running rigging. This should be done by crew after getting their assignment.

      - Trimmers
	- Rig headsail sheet. Based on your assessment of wind conditions, rig for genoa or Jib. We use the Genoa for wind less than 14kn and the jib when the wind is over 14 Kn. For the geneoa the sheets will go on the outside of the shrouds. For the jib they will go on the inside. Free the car c control lines and adjust the cars, but don't worry about getting them to the perfect spot since they won't stay in place without some load.

          The sheets go loosely wrapped around the primary winches. The car control lines go on the bench next to the bulkhead.

        - Loosely tie the working end of the sheets around the front of the mast using a square knot.

      - Foredeck
	- Rig the guys then the sheets for a starboard tack hoist. This means the gear will be on the port side. The guys run to the large blocks just behind the mid ship cleat then place the remaining control end of the line behind primary winch and on the deck between the bench and traveler. The sheets need to be above all other lines the run to the block on the stern coming from the outside to the inside, behind the primary winch up to the cabin top and down the companionway. There are red and green lines. The red lines go on port, the green lines go on starboard.

	  - Rig the tweakers

      - Pit
	- bring up winch handles
	- remove old course table and apply new course tape
	- uncoil and arrange lines
	- make sure you are familiar with the control lines

      - Main
	- uncoil and arrange main sheets, traveler control lines, and backstay control lines.


   1. Remove items
      At this point people should be more or less done with the rigging and we will form a line from the inside of the boat to the dock and remove the dehumidifies and heater. There are three dehumidifiers and one heater. The small dehumidifiers and heater can go in the dock box. The large dehumidifier can go behind the dock box. If it is raining cover the dehumidifier with the boom tent that is in the dock box. Make sure it is secure and will not blow away.

   2. Stow bags
      Using the same line pass the bags up into the boat. Bags should be stored near the butt of the mast for best weight distribution.

   3. Disembark
      Once you hear the engine start, be aware that we will be disembarking within 5 minutes. Three or four crew who are not otherwise busy should prepare the boat to leave the dock.

      - remove starboard fend and all but one of the port fenders. Leave the fender closest to the widest part of the boat. Tie the fenders to the dock. You may have to temporarily remove dock lines to tie the fenders down.

      - Remove starboard bow line from the boat and leave on dock. Do not untie from dock.

      - Remove forward spring line and bring on boat.

      - Remove rear spring line. It will still be attached to the boat as a stern line. Untie from the rear cleat but leave in cleat and hand back to the helm. 

      - When given the order from the helm, remove the port bow line from the boat and place on dock. Do not untie from dock.

      - Get on board

      - As we move out of the lane try to keep low and quiet and watch for boats pulling out of their slips. After we get to the main lane, remove the final fender and line. At this point it is OK to attache the main halyard to the main.



